tasks:
  - init: |
      echo "Intalling mkdocs"
      pip3 install mkdocs
    command: |
      echo "Building docs"
      mkdocs serve
  - command: |
      echo "Open ambianic docs preview."
      gp await-port 8000 && gp preview $(gp url 8000)/
