site_name: Ambianic Documentation
repo_url: https://github.com/ambianic/ambianic-docs
edit_uri: https://github.com/ambianic/ambianic-docs/edit/master/docs-md/
nav:
    - Home: index.md
    - User Guide:
      - Quick Start: users/quickstart.md
      - Ambianic Box: users/ambianicbox.md
      - Configuration: users/configure.md
      - Premium Services: users/premium-services.md
#      - FAQ: users/faq.md
#      - Web UI: users/webui.md
#      - Mobile UI: users/mobileui.md
#      - AI Apps: users/ai-apps.md
#      - How To: users/howto.md
#      - Support: users/support.md
      - Local and Remote pairing: users/edge-pairing.md
      - Home Assistant Integration: users/hass-integration.md
    - Developer Guide:
      - High Level System Architecture: developers/architecture.md
#      - APIs: developers/api.md
#      - Integrations: developers/integration.md
#      - Writing PLugins: developers/writing-plugins-overview.md
#      - Deployment Scenarios: developers/deployment.md
      - Contributing: 
        - Guidelines: legal/CONTRIBUTING.md
        - Setting up Your Dev Environment: developers/development-environment.md
      - Ambianic UI: https://github.com/ambianic/ambianic-ui
      - Ambianic Edge: 
        - Python API Reference: https://ambianic.github.io/ambianic-edge/ambianic/
        - Gtihub repo: https://github.com/ambianic/ambianic-edge
      - Ambianic Box: https://github.com/ambianic/ambianic-box
      - Fall Detection: https://github.com/ambianic/fall-detection
      - Peer to Peer Communication: 
        - p2p architecture: https://webrtchacks.com/private-home-surveillance-with-the-webrtc-datachannel/
        - peerjs-python: https://github.com/ambianic/peerjs-python
        - ambianic-pnp: https://github.com/ambianic/ambianic-pnp
      - Premium Service Cloud API:
          - Cloud API Documentation: https://github.com/vickywane/ambianic-subscriptions.github.io/tree/main/openapi-docs#installation
          - OpenAPI Documentation: https://ambianic.github.io/ambianic-subscriptions.github.io/

theme:
    name: mkdocs
    custom_dir: custom_theme/
copyright: Ambianic.ai &copy; 2019-2021
docs_dir: docs-md

markdown_extensions:
  - admonition
# extra_css:
#  - assets/flowchart.css
# extra_javascript:
#  - assets/raphael.min.js
#  - assets/flowchart.min.js
#  - assets/jquery-plugin.js
