site_name: Ambianic Documentation
repo_url: https://github.com/ambianic/ambianic-docs
edit_uri: https://github.com/ambianic/ambianic-docs/edit/master/docs-md/
nav:
    - Home: index.md
    - User Guide:
      - Quick Start: users/quickstart.md
      - Ambianic Box: users/ambianicbox.md
      - Configuration: users/configure.md
#      - FAQ: users/faq.md
#      - Web UI: users/webui.md
#      - Mobile UI: users/mobileui.md
#      - AI Apps: users/ai-apps.md
#      - How To: users/howto.md
#      - Support: users/support.md
      - Local and Remote pairing: users/edge-pairing.md
      - Home Assistant Integration: users/hass-integration.md
    - Developer Guide:
      - High Level System Architecture: developers/architecture.md
      - Development Environment Setup: developers/development-environment.md
      - End to End System Testing in Dev Mode: developers/e2e-manual-testing.md
      - Contribution Guidelines: legal/CONTRIBUTING.md
      - Ambianic UI git repo: https://github.com/ambianic/ambianic-ui
      - Ambianic Edge: 
        - Core Git Repo: https://github.com/ambianic/ambianic-edge
        - Python API: https://ambianic.github.io/ambianic-edge/pythonapi/ambianic/
        - OpenAPI(REST): https://ambianic.github.io/ambianic-edge/openapi/ambianic-edge-openapi.html
        - Fall Detection Model: https://github.com/ambianic/fall-detection
        - Command Line Interface: https://github.com/ambianic/ambianic-quickstart
        - Operating System: https://github.com/ambianic/ambianic-rpi-image
        - Physical Enclosure: https://github.com/ambianic/ambianic-box
      - Peer to Peer Communication: 
        - p2p architecture: https://webrtchacks.com/private-home-surveillance-with-the-webrtc-datachannel/
        - peerjs-python git repo: https://github.com/ambianic/peerjs-python
        - ambianic-pnp git repo: https://github.com/ambianic/ambianic-pnp
#      - APIs: developers/api.md
#      - Integrations: developers/integration.md
#      - Writing PLugins: developers/writing-plugins-overview.md
#      - Deployment Scenarios: developers/deployment.md
      
theme:
    name: mkdocs
    custom_dir: custom_theme/
copyright: Ambianic.ai &copy; 2019-2021
docs_dir: docs-md
# extra_css:
#  - assets/flowchart.css
# extra_javascript:
#  - assets/raphael.min.js
#  - assets/flowchart.min.js
#  - assets/jquery-plugin.js
