site_name: Ambianic Documentation
repo_url: https://github.com/ambianic/ambianic-docs
edit_uri: https://github.com/ambianic/ambianic-docs/edit/master/docs-md/
nav:
    - Home: index.md
    - User Guide:
      - Quick Start: users/quickstart.md
      - Ambianic Box: users/ambianicbox.md
      - Configuration: users/configure.md
#      - FAQ: users/faq.md
#      - Web UI: users/webui.md
#      - Mobile UI: users/mobileui.md
#      - AI Apps: users/ai-apps.md
#      - How To: users/howto.md
#      - Support: users/support.md
      - Remote / Local connection: users/edge-pairing.md
    - Developer Guide:
      - Development Environment: developers/development-environment.md
      - Architecture: developers/architecture.md
#      - APIs: developers/api.md
#      - Integrations: developers/integration.md
#      - Writing PLugins: developers/writing-plugins-overview.md
#      - Deployment Scenarios: developers/deployment.md
      - Contributing: legal/CONTRIBUTING.md
theme:
    name: mkdocs
    custom_dir: custom_theme/
copyright: Ambianic.ai &copy; 2019-2020
docs_dir: docs-md
# extra_css:
#  - assets/flowchart.css
# extra_javascript:
#  - assets/raphael.min.js
#  - assets/flowchart.min.js
#  - assets/jquery-plugin.js
